# frozen_string_literal: true
source "https://rubygems.org"

group :development, :test do
  gem "rake"
  gem "pry" # Easily debug from your console with `binding.pry`
  gem "pry-byebug", platform: :mri # Step-by-step debugging

  gem "cancancan"
  gem "pundit"
  gem "jruby-openssl", platform: :jruby

  gem "draper"
  gem "devise", ">= 4.9.0"

  gem "rails", "~> 7.0.8", ">= 7.0.8.1"
  gem "activerecord-jdbcsqlite3-adapter", platform: :jruby

  gem "net-smtp" # The mail gem, depended on transitively, does not specify this dependency

  gem "webpacker", ">= 5.4.4"
end

group :test do
  gem "cuprite", ">= 0.14.3"
  gem "capybara", ">= 3.37.0"
  gem "webrick"

  gem "simplecov", require: false # Test coverage generator. Go to /coverage/ after running tests
  gem "cucumber-rails", ">= 3.0.0", require: false
  gem "cucumber"
  gem "database_cleaner"
  gem "jasmine", ">= 3.0.0"
  gem "jasmine-core"
  gem "launchy"
  gem "parallel_tests"
  gem "rails-i18n" , ">= 7.0.6" # Provides default i18n for many languages
  gem "rspec-rails", ">= 6.0.2"
  gem "sqlite3", platform: :mri
end

gemspec path: "../.."
